# Generated by Django 5.2.1 on 2025-05-30 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='joined_date',
            new_name='join_date',
        ),
    ]
